name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  provider: ^6.1.2
  go_router: ^14.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/noimage.jpg

  fonts:
    - family: Lexend
      fonts:
      - asset: assets/fonts/Lexend-Black.ttf
      - asset: assets/fonts/Lexend-Bold.ttf
      - asset: assets/fonts/Lexend-ExtraBold.ttf
      - asset: assets/fonts/Lexend-ExtraLight.ttf
      - asset: assets/fonts/Lexend-Medium.ttf
      - asset: assets/fonts/Lexend-Regular.ttf
      - asset: assets/fonts/Lexend-Semibold.ttf
      - asset: assets/fonts/Lexend-Thin.ttf
